background = #243031
foreground = #dcd6ce
cursor-color = #f5f1e8
selection-background = #2c3547
selection-foreground = #f5f1e8

palette = 0=#1a1f2b
palette = 1=#55d8c5
palette = 2=#4cd5b5
palette = 3=#23ac97
palette = 4=#9ff0d5
palette = 5=#abf6fd
palette = 6=#77e0f8
palette = 7=#ffffff
palette = 8=#c8e1e4
palette = 9=#d9836f
palette = 10=#96b8a4
palette = 11=#ecc98c
palette = 12=#8ba5c4
palette = 13=#c29ebd
palette = 14=#85b7c0
palette = 15=#f5f1e8
