foreground #dcd6ce
background #243031
selection_foreground #f5f1e8
selection_background #2c3547

cursor #f5f1e8
cursor_text_color #1a1f2b

active_border_color #abfeff
active_tab_background #abfeff

color0 #1a1f2b
color1 #55d8c5
color2 #4cd5b5
color3 #23ac97
color4 #9ff0d5
color5 #abf6fd
color6 #77e0f8
color7 #ffffff
color8 #c8e1e4
color9 #d9836f
color10 #96b8a4
color11 #ecc98c
color12 #8ba5c4
color13 #c29ebd
color14 #85b7c0
color15 #f5f1e8
